name: LFS check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lfs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Verify LFS pointers exist
        run: |
          git lfs version
          git lfs ls-files --all
